version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: aura-finance-db
    environment:
      POSTGRES_DB: aura_finance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - aura-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aura-finance-backend
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/aura_finance
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      PORT: 3001
      NODE_ENV: development
      CORS_ORIGIN: http://localhost:5173
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - aura-network
    command: npm run dev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: aura-finance-frontend
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - aura-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  aura-network:
    driver: bridge
