name: CI/CD Pipeline

on:
  push:
    branches: [main, develop, feature/*, hotfix/*, release/*]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Test build process
        run: npm run test:build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.node-version }}
          path: dist/

  security:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: npm audit --audit-level=high

      - name: Run dependency check
        run: npx audit-ci --high

      - name: Run security vulnerability check
        run: npm run security

      - name: Install jq for JSON parsing
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Check for known vulnerabilities
        run: |
          echo "🔒 Security audit completed"
          echo "📊 Vulnerability Summary:"
          npm audit --audit-level=high --json | jq '.metadata.vulnerabilities' || echo "No vulnerabilities found or audit failed"

          echo ""
          echo "📋 Known Issues:"
          echo "- esbuild vulnerability (moderate): Development-only, planned for v1.2.0"
          echo "- See SECURITY.md for detailed information"
